### ISSUE TITLE
I build this myself with VS2019

### ISSUE THREAD

**Issue by oneleo** [MegaMagicPower/Another-Eden-Fish-Bot#2]
I cannot execute the AE_Fish_Bot.exe binary file(did nothing and the config "LDPlayer=" is correct) so I try to use vcpkg with VS2019(in Windows 10 Pro Ver. 1809) to install opencv[contrib]:x64-windows and tesseract:x64-windows

1. Install VS2019

2. Use 【x64 Native Tools Command Prompt for vS 2019】to Inatall vcpkg
>cd "C:\Users\chtti\Documents\vcpkg"
> .\bootstrap-vcpkg.bat
> .\vcpkg.exe integrate install

3. Install opencv[contrib]:x64-windows and tesseract:x64-windows
> vcpkg install tesseract:x64-windows
> vcpkg install opencv[contrib]:x64-windows --recurse

4. Set Global Environment Variable to use 64-bit tools forcely
> set VCPKG_DEFAULT_TRIPLET=x64-windows

5. Open new VS2019 project and copy Another-Eden-Fish-Bot code into it, then build them

--------------------------------------------------

But appear some errors below:
|    Severity    | Code  | Description                                                                                                                                                                                           | Project                  | File                                                                                                    | Line | Suppression State |
|:--------------:|-------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------|---------------------------------------------------------------------------------------------------------|------|-------------------|
| Error (active) | E0289 | no instance of   constructor "std::basic_string<_Elem, _Traits,   _Alloc>::basic_string [with _Elem=char,   _Traits=std::char_traits<char>,   _Alloc=std::allocator<char>]" matches the argument list | My-Another-Eden-Fish-Bot | C:\Users\chtti\Documents\My-Another-Eden-Fish-Bot\My-Another-Eden-Fish-Bot\My-Another-Eden-Fish-Bot.cpp | 114  |                   |
| Error (active) | E0167 | argument of type "TCHAR *" is   incompatible with parameter of type "LPSTR"                                                                                                                           | My-Another-Eden-Fish-Bot | C:\Users\chtti\Documents\My-Another-Eden-Fish-Bot\My-Another-Eden-Fish-Bot\My-Another-Eden-Fish-Bot.cpp | 120  |                   |
| Error (active) | E0349 | no operator "=" matches these   operands                                                                                                                                                              | My-Another-Eden-Fish-Bot | C:\Users\chtti\Documents\My-Another-Eden-Fish-Bot\My-Another-Eden-Fish-Bot\My-Another-Eden-Fish-Bot.cpp | 121  |                   |
| Error (active) | E0167 | argument of type "TCHAR *" is   incompatible with parameter of type "LPSTR"                                                                                                                           | My-Another-Eden-Fish-Bot | C:\Users\chtti\Documents\My-Another-Eden-Fish-Bot\My-Another-Eden-Fish-Bot\My-Another-Eden-Fish-Bot.cpp | 137  |                   |
| Error (active) | E0415 | no suitable constructor exists to convert   from "TCHAR [260]" to "std::basic_string<char,   std::char_traits<char>, std::allocator<char>>"                                                           | My-Another-Eden-Fish-Bot | C:\Users\chtti\Documents\My-Another-Eden-Fish-Bot\My-Another-Eden-Fish-Bot\My-Another-Eden-Fish-Bot.cpp | 138  |                   |

Thanks!

**Comment by oneleo** [comment]
I found the encode solution:
1. In the Project Property Pages, select "Use Multi-Byte Character Set" at Advanced - Character Set

But it still appear an error:
OCRTesseract(07): Tesseract not found.

How can I build OpenCV with Tesseract so that use OCRTesseract function?

The document
https://tesseract-ocr.github.io/tessdoc/Compiling
cannot work(with cppan.exe), too.

Thanks

**Comment by MegaMagicPower** [comment]
I think this comment I left will help. Building OpenCV With Tesseract is the hardest part of this process. You will probably save a lot of time if you just download the precompiled version of OpenCV I linked at the google drive link and follow the instructions in Visual Studio to link it properly. The next time I update this I will put a link to the google drive link and the instructions in that comment since I now realize its a pain to do yourself. Sorry for the trouble.

https://www.reddit.com/r/AnotherEdenGlobal/comments/dgpe0n/automated_fishing_bot/f9kexgg/

**Comment by oneleo** [comment]
I understood! Many Thanks! I will try this tips to build, and look forward to your next version.
Thank you again!
